# Generated by Django 5.2.3 on 2025-09-09 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("noombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                ("nacionalidad", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("fecha_publicacion", models.DateField()),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("ficcion", "Ficción"),
                            ("no_ficcion", "No Ficción"),
                            ("fantasia", "Fantasía"),
                            ("ciencia", "Ciencia"),
                            ("historia", "Historia"),
                            ("biografia", "Biografía"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("paginas", models.IntegerField()),
                ("disponible", models.BooleanField(default=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="libros",
                        to="biblioteca.autor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_prestamo", models.DateField(auto_now_add=True)),
                ("fecha_devolucion", models.DateField(blank=True, null=True)),
                ("devuelto", models.BooleanField(default=False)),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.libro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
