# Generated by Django 5.2.3 on 2025-09-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="autor",
            old_name="noombre",
            new_name="nombre",
        ),
    ]
